version: "3.8"

services:
  main:
    container_name: main
    build:
      context: './api'
      dockerfile: ./Dockerfile
    volumes:
      - .env:/usr/src/app/.env
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  web-admin:
    container_name: "web-admin"
    image: "web-admin"
    build:
      context: "./client"
      dockerfile: ./Dockerfile
    ports:
      - '8083:80'

volumes:
  pgdata: