version: '3.8'

services:
  postgres:
    image: postgres:14.2
    restart: always
    env_file:
      - .env
    ports:
      - "5532:5532"
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: './api'
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api
    ports:
      - '3001:3000'

  client:
    build:
      dockerfile: Dockerfile
      context: "./client"
    depends_on:
      - api
    volumes:
      - /client/node_modules
      - ./client:/app
    ports:
      - "5173:5173"

volumes:
  pg_data: