version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  api:
    build:
      dockerfile: Dockerfile
      context: './api'
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=11012346QWERty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - /api/node_modules
      - ./api:/api

#  client:
#    build:
#      dockerfile: Dockerfile
#      context: "./client"
##    depends_on:
##      - api
#    volumes:
#      - /client/node_modules
#      - ./client:/app
#    ports:
#      - "5173:5173"

volumes:
  pg_data: